- name: template snic file server
  template: 
    src: roles/software-repository/files/siebel-{{target_platform}}.rsp.j2
    dest: /tmp/siebel-{{target_platform}}.rsp

- name: template snic file win
  template: 
    src: roles/software-repository/files/siebel-win.rsp.j2
    dest: /tmp/siebel-win.rsp
 
- name: check if we ran before server
  stat:
    path: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/products.txt"
  register: server_install_image

- name: check if we ran before win
  stat:
    path: "{{ software_repository_path }}/siebel-win-{{ siebel_version }}/Siebel_Install_Image/products.txt"
  register: win_install_image

- name: run snic.sh server
  command: ./snic.sh -silent -responseFile /tmp/siebel-{{target_platform}}.rsp
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/unarchive"
  when:
    server_install_image.stat.exists == false
  environment:
    JAVA_HOME: "{{java_home}}"
    LANG: "C"

- name: run snic.sh win
  command: ./snic.sh -silent -responseFile /tmp/siebel-win.rsp
  args:
    chdir: "{{ software_repository_path }}/siebel-win-{{ siebel_version }}/unarchive"
  when:
    win_install_image.stat.exists == false
  environment:
    JAVA_HOME: "{{java_home}}"
    LANG: "C"


