---
# tasks file for siebel server

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/ses/oraInventory/"

- name: create siebel ses oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ses/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ses/oraInventory
       inst_group=siebel

- name: template install ses response file
  template: 
    src: roles/siebel-server/files/siebel-{{siebel_version}}-install-ses.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ses.rsp

- name: install ses
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ses.rsp -jreloc {{java_home}} -invPtrLoc {{siebel_base_path}}/ses/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{ siebel_version }}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/Siebel/ses/siebsrvr"

- name: check existing siebel database
  shell : "source /home/siebel/.bash_profile && echo 'select name from siebel.s_repository;' | sqlplus sadmin/nimdas@orcl"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
  register: siebel_database_exists

- name: create siebel database
  include: create-siebel-database.yml
  when: siebel_database_exists.stdout.find("Siebel Repository") == -1

- name: wait for tomcat to come up
  wait_for:
    port: 8100
    delay: 10
    state: started

- name: shutdown gateway
  shell : "{{siebel_base_path}}/ses/Siebel/ses/applicationcontainer/bin/shutdown.sh"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"

- name: wait for tomcat to stop
  wait_for:
    port: 8102
    delay: 10
    state: stopped

- name: move vanilla jre out of the way
  command: mv {{siebel_base_path}}/ses/Siebel/ses/jre {{siebel_base_path}}/ses/Siebel/ses/jre_orig
  args:
    creates: "{{siebel_base_path}}/ses/Siebel/ses/jre_orig"

- name: link system jre
  file:
    src: "{{java_home}}/jre"
    dest: "{{siebel_base_path}}/ses/Siebel/ses/jre"
    state: link

- name: start tomcat
  shell : "source /home/siebel/.bash_profile && {{siebel_base_path}}/ses/Siebel/ses/applicationcontainer/bin/startup.sh"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{siebel_base_path}}/ses/Siebel/ses/applicationcontainer"
    executable: "/usr/bin/bash"

- name: wait for tomcat to start
  wait_for:
    port: 8102
    delay: 10
    state: started